artifact_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name_elastic_net: elastic_net_model.joblib
  model_name_linear_regression: linear_regression_model.joblib
  model_name_support_vector: support_vector_model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  elastic_net_model_path: artifacts/model_trainer/elastic_net_model.joblib
  linear_regression_model_path: artifacts/model_trainer/linear_regression_model.joblib
  support_vector_machine_model_path: artifacts/model_trainer/support_vector_model.joblib
  metrics_file_name: artifacts/model_evaluation/metrics.json

  